name: ci

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main 
      - development 

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]
        laravel: ["^8.0", "^9.0"]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --with='laravel/framework:${{ matrix.laravel }}' --prefer-dist --no-interaction --no-progress

      - name: Check autoloading
        run: |
          composer self-update --snapshot
          composer dump-autoload --optimize --strict-psr --dev
          composer self-update --rollback

      - name: Execute static analysis
        run: composer run types

      - name: Execute tests
        run: composer run tests

      - name: Check formatting
        run: composer run format -- --test


    